INSERT INTO SPECIALTY (ID, SPECIALTYNAME, CERTIFICATE,MINDURATION) VALUES (1, 'Fisioterapia','FIS0',20)
INSERT INTO SPECIALTY (ID, SPECIALTYNAME, CERTIFICATE,MINDURATION) VALUES (2, 'Massagem Desportiva','MASG',30)
INSERT INTO SPECIALTY (ID, SPECIALTYNAME, CERTIFICATE,MINDURATION) VALUES (3, 'Pilates Clinico','FIS1',40)
INSERT INTO SPECIALTY (ID, SPECIALTYNAME, CERTIFICATE,MINDURATION) VALUES (4, 'Pos Parto','FIS0',30)

